### ISSUE TITLE
yiisoft/yii2-jui required?

### ISSUE THREAD

**Issue by AndiP-IoT** [xjflyttp/yii2-tagit-widget#1]
I tried yii2-tagit-widget and ran into a problem.

> Error Class yii\jui\JuiAsset does not exist

So I had to install jui\JuiAsset

> composer require --prefer-dist yiisoft/yii2-jui
> and everithing worked

I do not know, if _jui\JuiAsset_ should allready be included in yii2 ?
Maybe the hint about requiremend of _jui\JuiAsset_ should be included in _README.md_

I use _composer create-project --prefer-dist yiisoft/yii2-app-advanced yii_advanced_

**Comment by xjflyttp** [comment]
yes, you need require yiisoft/yii2-jui
require missing in composer.json
now fix this problem. thanks.
